marketplace/conversation/urls.py
from django.urls import path
from . import views


app_name='conversation'

urlpatterns = [
    path('new/<int:item_pk>/',views.new_conversation, name="new"),
    path('<int:pk>/',views.detail, name="detail"),
    path('',views.inbox, name="inbox"),
]

marketplace/item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('',views.items, name='items'),
    path('new/',views.new, name='new'),
    path('<int:pk>/',views.detail, name='detail'),
    path('<int:pk>/delete/',views.delete, name='delete'),
    path('<int:pk>/edit/',views.edit, name='edit')
]

marketplace/marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import index, contact
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('items/',include('item.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

marketplace/item/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length = 255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = "categories"
    def __str__(self):
        return self.name
    


class Item(models.Model):
    name = models.CharField(max_length = 255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    is_sold = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to="items_images", blank=True, null=True)
    created_by = models.ForeignKey(User, related_name="items", on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name="items", on_delete=models.CASCADE)

    def __str__(self):
        return self.name

marketplace/item/forms.py
from django import forms
from .models import Item

CLASS_TAILWIND = 'w-full px-4 py-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image',)
        widgets = {
            'category' : forms.Select(attrs={
                'class' : CLASS_TAILWIND
            }),
            'name' : forms.TextInput(attrs={
                'class' : CLASS_TAILWIND
            }),
            'description' : forms.Textarea(attrs={
                'class' : CLASS_TAILWIND
            }),
            'price' : forms.TextInput(attrs={
                'class' : CLASS_TAILWIND
            }),
            'image' : forms.FileInput(attrs={
                'class' : CLASS_TAILWIND
            }),

            

        }





class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'image', 'is_sold')
        widgets = {
            'name' : forms.TextInput(attrs={
                'class' : CLASS_TAILWIND
            }),
            'description' : forms.Textarea(attrs={
                'class' : CLASS_TAILWIND
            }),
            'price' : forms.TextInput(attrs={
                'class' : CLASS_TAILWIND
            }),
            'image' : forms.FileInput(attrs={
                'class' : CLASS_TAILWIND
            }),
            
        }

marketplace/item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Item,Category
from .forms import NewItemForm, EditItemForm
from   django.db.models import Q



def items(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    items = Item.objects.filter(is_sold=False)
    categories = Category.objects.all()

    if query:
        items = items.filter(Q(name__icontains=query) | Q(description__icontains=query))
    if category_id:
        items = items.filter(category_id=category_id)
    return render(request, 'item/items.html', {
        'items':items,
        'query':query,
        'categories':categories,
        'category_id':int(category_id),
        
    })





def detail(request,pk):
    item = get_object_or_404(Item,pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]
    return render(request, 'item/detail.html',{
        'item':item,
        'related_items' : related_items
    })


@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST,request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            return redirect('item:detail',pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'item/form.html', {
        'form' : form
    })



@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    if request.method == 'POST':
        form = EditItemForm(request.POST,request.FILES, instance=item)
        if form.is_valid():
            form.save()
            return redirect('item:detail',pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'form' : form
    })




@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()
    return redirect('dashboard:index')

marketplace/item/templates/item/detail.html
{% extends "main/base.html" %}

{% block title %}{{item.name}}{% endblock title %}

{% block content %}



<div class="container mx-auto p-6">
    <div class="md:flex md:items-start md:space-x-8">
        <!-- Product Image -->
        <div class="md:w-1/2 lg:w-1/3">
            <img class="rounded-lg shadow-lg w-full h-100 object-cover" src="{{item.image.url}}" alt="Product Image">

        </div>

        <!-- Product Details -->
        <div class="md:w-1/2 lg:w-2/3 mt-4 md:mt-0 bg-gray-200 px-4 py-4 rounded-lg shadow-lg">
            
            <h2 class="text-4xl font-bold">{{item.name}}</h2>
            <p class="text-gray-700 text-base">${{item.price}}</p>

            <p class="text-gray-600 mt-2">Seller <span class="font-semibold">{{item.created_by.username}}</span></p>
            <p class="text-gray-600">Category: <span class="font-semibold">{{item.category.name}}</span></p>
            <div class="mt-4 mb-6">
                <p class="text-gray-700 text-base mb-4">Detailed description</p>
                <p>
                    {{item.description}}
                </p>
            </div>
            {% if request.user == item.created_by %}

                <a href='{% url "item:edit" item.id %}'>
                <button class="bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                    Edit Item
                </button>
                    </a>


                    <a href='{% url "item:delete" item.id %}'>
                    <button class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                        Delete Item
                    </button>
                        </a>
            {% else %}
                    <a href='{% url "conversation:new" item.id %}'>
                    <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
                        Contact Seller
                    </button>
                    </a>
            {% endif %}
        </div>
    </div>



    <h2 class="text-2xl font-bold mt-4 mb-2 text-center text-gray-700">Related items</h2>
    <div class="grid md:grid-cols-3 gap-4 mt-10">
        <!-- Product Card  -->
        

    {% for item in related_items %}
    <a href='{% url "item:detail" item.id %}'>
        <div class="max-w-sm rounded overflow-hidden shadow-lg cursor-pointer hover:shadow-2xl transition duration-300 ease-in-out">
            <img class="w-full h-40 object-cover" src="{{item.image.url}}" alt="Product Image">
            <div class="px-6 py-4">
                <div class="font-bold text-xl mb-2">{{item.name}}</div>
                <p class="text-gray-700 text-base">${{item.price}}</p>
            </div>
        </div>
    </a>
        {% endfor %}
        
    </div>
</div>


{% endblock content %}

marketplace/item/templates/item/form.html
{% extends "main/base.html" %}

{% block title %}New Item{% endblock title %}

{% block content %}
<div class="bg-gray-100 mx-auto">
    <div class="bg-white rounded-lg shadow-md p-6">
        <h2 class="text-center text-3xl font-extrabold text-gray-900 mb-6">New Item</h2>
        <form action="." method="POST" enctype='multipart/form-data'>
        {% csrf_token %}
       
        {{ form.as_p }}
        

        

{% if form.errors or form.non_field_errors %}
<div class="bg-red-100 rounded-xl mb-3 p-6">
   {% for field in  form %}
   {{field.errors}}
   {% endfor %}
   {{ form.non_field_errors}}
</div>
{% endif %}

            <div class="flex items-center justify-between">
                <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full">add Item</button>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

marketplace/item/templates/item/items.html
{% extends "main/base.html" %}

{% block title %}items{% endblock title %}


{% block content %}
<div class="container mx-auto p-4">
    <div class="flex">
        <div class="w-64 h-screen bg-gray-800 text-white p-4">
            <div class="flex flex-col">
                <!-- Sidebar content here -->
                <form method="GET" class="" action="{% url "item:items" %}">
                    
                        <input value="{{query}}"type="text" name='query' class="bg-gray-700 w-full px-4 py-2 rounded-xl outline-none" placeholder="Search...">
                        <button class="bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline mt-2">
                            Search
                        </button>
                    
                </form>
                
            </div>
            <div class="flex flex-col mt-2">
                <!-- Sidebar content here -->
                <h2 class="text-teal-200 px-6 py-4">Categories</h2>
                {% for category in categories %}
                        <a href="{% url 'item:items' %}?query={{ query }}&category={{ category.id }}" class="py-2 px-4 {% if category.id == category_id %} bg-gray-700{% endif %}">{{category.name}}</a>
                {% endfor %}
            </div>
    
        </div>
        <div class="flex-1 p-4">
            <div class="grid md:grid-cols-3 gap-4">
                <!-- Product Card  -->
        
            {% for item in items %}
            <a href='{% url "item:detail" item.id %}'>
                <div class="max-w-sm rounded overflow-hidden shadow-lg cursor-pointer hover:shadow-2xl transition duration-300 ease-in-out">
                    <img class="w-full h-80 object-cover" src="{{item.image.url}}" alt="Product Image">
                    <div class="px-6 py-4">
                        <div class="font-bold text-xl mb-2">{{item.name}}</div>
                        <p class="text-gray-700 text-base">${{item.price}}</p>
                    </div>
                </div>
            </a>
                {% endfor %}
                
            </div>
        </div>
    </div>
    
    





    
       
    
    
</div>



{% endblock content %}
  