marketplace/conversation/urls.py
from django.urls import path
from . import views


app_name='conversation'

urlpatterns = [
    path('new/<int:item_pk>/',views.new_conversation, name="new"),
    path('<int:pk>/',views.detail, name="detail"),
    path('',views.inbox, name="inbox"),
]

marketplace/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
]

marketplace/item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('',views.items, name='items'),
    path('new/',views.new, name='new'),
    path('<int:pk>/',views.detail, name='detail'),
    path('<int:pk>/delete/',views.delete, name='delete'),
    path('<int:pk>/edit/',views.edit, name='edit')
]

marketplace/main/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm

app_name = 'main'

urlpatterns = [
    path('',views.index, name='index'),
    path('contact/',views.contact, name='contact'),
    path('signup/',views.signup, name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='main/login.html',authentication_form=LoginForm), name='login'),
]

marketplace/marketplace/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import index, contact
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('items/',include('item.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('inbox/',include('conversation.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

marketplace/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User





class LoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder' : 'enter your username',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'enter your password',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = {'username','email','password1','password2'}
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder' : 'enter your username',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))


    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder' : 'enter your email',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))


    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'enter your password',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))


    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder' : 'repeat your pasword',
        'class' : 'w-full py-4 px-6 rounded-xl'
    }))

marketplace/main/views.py
from django.shortcuts import render, redirect
from item.models import Category, Item
from .forms import SignupForm

def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(request, "main/index.html", {
        "categories" : categories,
        "items" : items
    })



def contact(request):
    return render(request, 'main/contact.html')



def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('/login')
    else:
        form = SignupForm()
    return render(request, 'main/signup.html', {'form':form})

marketplace/main/templates/main/base.html
<!DOCTYPE html>
<html>
<head>
    
    <meta charset="UTF-8">
    <meta name="description" content="A brief description of your page">
    <meta name="keywords" content="HTML, CSS, JavaScript">
    <meta name="author" content="Your Name">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>{% block title %}{% endblock title %}</title>
</head>
<body class="bg-gray-100">



    <nav class="bg-gray-800 p-4">
        <div class="container mx-auto flex justify-between items-center">
            <a href="{% url "main:index" %}"><div class="text-white font-semibold text-lg">MarketPlace</div></a>
            
            <div class="flex items-center">
                <a href="{% url "item:new" %}" class="text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium">New Item</a>
                <a href="{% url "item:items" %}" class="text-gray-300 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Browse</a>


                {% if request.user.is_authenticated %}

                    <a href="{% url "conversation:inbox" %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium ml-4">Inbox</a>
                    <a href="{% url "dashboard:index" %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Dachboard</a>
                {% else %}
                        <a href="{% url "main:signup" %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium ml-4">Sign Up</a>
                        <a href="{% url "main:login" %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Login</a>
                {% endif %}
            </div>
        </div>
    </nav>
    
    <div class="px-4 py-2">
        {% block content %}
        
        {% endblock content %}
      </div>


      <footer class="bg-gray-800 text-white py-6">
        <div class="container mx-auto px-4 flex justify-between">
            <div>
                <ul>
                    <li class="mb-2"><a href="{% url "main:contact" %}" class="hover:text-gray-400">Contact</a></li>
                    <li class="mb-2"><a href="#" class="hover:text-gray-400">About</a></li>
                    <li class="mb-2"><a href="#" class="hover:text-gray-400">Terms of Use</a></li>
                </ul>
            </div>
            <div>
                
            </div>
        </div>
    </footer>
    
</body>
</html>

marketplace/main/templates/main/contact.html
{% extends "main/base.html" %}

{% block title %}Contact{% endblock title %}


{% block content %}
<h1>Contact page</h1>

{% endblock content %}

marketplace/main/templates/main/index.html
{% extends "main/base.html" %}

{% block title %}Home{% endblock title %}


{% block content %}
<div class="container mx-auto p-4">
    <div class="grid md:grid-cols-3 gap-4">
        <!-- Product Card  -->

    {% for item in items %}
    <a href='{% url "item:detail" item.id %}'>
        <div class="max-w-sm rounded overflow-hidden shadow-lg cursor-pointer hover:shadow-2xl transition duration-300 ease-in-out">
            <img class="w-full h-80 object-cover" src="{{item.image.url}}" alt="Product Image">
            <div class="px-6 py-4">
                <div class="font-bold text-xl mb-2">{{item.name}}</div>
                <p class="text-gray-700 text-base">${{item.price}}</p>
            </div>
        </div>
    </a>
        {% endfor %}
        
    </div>





    
        <div class="grid md:grid-cols-3 gap-4">
            <!-- Category 1 -->

            {% for category in categories %}
            <a href='{% url 'item:items' %}?query={{ query }}&category={{ category.id }}'>
            <div class="rounded overflow-hidden shadow-lg hover:shadow-2xl transition duration-300 ease-in-out">
                <div class="px-6 py-4">
                    <div class="font-bold text-xl mb-2">{{category.name}}</div>
                    <p class="text-gray-700 text-base">{{category.items.count}} items</p>
                </div>
            </div>
        </a>
            {% endfor %}
        </div>
    
    
</div>



{% endblock content %}
  

marketplace/main/templates/main/login.html
{% extends "main/base.html" %}

{% block title %}login{% endblock title %}


{% block content %}

<div class="bg-gray-100 flex items-center justify-center h-screen">
    <div class="max-w-md w-full bg-white rounded-lg shadow-md p-6">
        <h2 class="text-center text-3xl font-extrabold text-gray-900 mb-6">login</h2>
        <form action="." method="POST">
        {% csrf_token %}
       
        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="email">username</label>
        {{form.username}}
        </div>


        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="email">password</label>
        {{form.password}}
        </div>

        

{% if form.errors or form.non_field_errors %}
<div class="bg-red-100 rounded-xl mb-3 p-6">
   {% for field in  form %}
   {{field.errors}}
   {% endfor %}
   {{ form.non_field_errors}}
</div>
{% endif %}

            <div class="flex items-center justify-between">
                <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full">login</button>
            </div>
        </form>
    </div>
</div>



{% endblock content %}

marketplace/main/templates/main/signup.html
{% extends "main/base.html" %}

{% block title %}SignUp{% endblock title %}


{% block content %}

<div class="bg-gray-100 flex items-center justify-center h-screen">
    <div class="max-w-md w-full bg-white rounded-lg shadow-md p-6">
        <h2 class="text-center text-3xl font-extrabold text-gray-900 mb-6">Sign Up</h2>
        <form action="." method="POST">
        {% csrf_token %}
       
        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="email">username</label>
        {{form.username}}
        </div>

        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="email">Email</label>
        {{form.email}}
        </div>

        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="email">password</label>
        {{form.password1}}
        </div>

        <div class="mb-4">
            <label class="block text-gray-700 text-sm font-bold mb-2" for="email">repeat password</label>
        {{form.password2}}
        </div>

{% if form.errors or form.non_field_errors %}
<div class="bg-red-100 rounded-xl mb-3 p-6">
   {% for field in  form %}
   {{field.errors}}
   {% endfor %}
   {{ form.non_field_errors}}
</div>
{% endif %}

            <div class="flex items-center justify-between">
                <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline w-full">Sign Up</button>
            </div>
        </form>
    </div>
</div>



{% endblock content %}